### ISSUE TITLE
Not able to run the generator 

### ISSUE THREAD

**Issue by dedaluz** [davidhellmann/generator-dhBoilerplate#14]
It seems these lines break it for me: 

        var gitInfo = {
            name: exec('git config user.name', {silent: true}).replace(/\n/g, ''),
            email: exec('git config user.email', {silent: true}).replace(/\n/g, ''),
            github: exec('git config github.user', {silent: true}).replace(/\n/g, '')
        }

With the error message by Yo:

`ReferenceError: exec is not defined`

**Comment by davidhellmann** [comment]
Thanks for reporting @dedaluz

**Comment by dedaluz** [comment]
Still failing for me.

And thank you. This generator seems amazing to me, although there's many parts I don't understand yet. I can see it as being a de facto standard for every Craft CMS project.

**Comment by davidhellmann** [comment]
Can you post the error Message or a Screenshot. Or maybe retry NPM Link / Update the Generator?

**Comment by dedaluz** [comment]
It seems it's that use of exec() ?

<img width="1043" alt="screenshot 2017-02-23 10 48 04" src="https://cloud.githubusercontent.com/assets/26007/23253657/a97f9eaa-f9b5-11e6-826a-29b9545e5a7d.PNG">

**Comment by davidhellmann** [comment]
@dedaluz ok I published again and comment out this part. Hope it's fine now.

**Comment by dedaluz** [comment]
Working great. :)
