### ISSUE TITLE
New Update having bugs ?

### ISSUE THREAD

**Issue by melaniegravelnurun** [davidhellmann/generator-dhBoilerplate#21]
Since I updated, I get this error: 
```
node_modules/critical/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:6
const _buff = Buffer.alloc(BUF_LENGTH)... 
```

And even when I remove this dependency completely, I still get compilation error with the task 'sass' and 'babel-register'. Is there something I am missing?

**Comment by davidhellmann** [comment]
Hey @melaniegravelnurun 
do you use it with Craft? Craft Beta? And when comes this error? What do you do? :)

Cheers

**Comment by melaniegravelnurun** [comment]
Yeah, I realize I was not being really clear! 😄 

I use it with Prototyping, no Imager, with jQuery and Vue.

Then I run ‘npm install’ (which has errors because of the trailing and missing commas, but easy to fix), and then ‘npm start’.

That's when I get 

```
/node_modules/critical/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:6
const _buff = Buffer.alloc(BUF_LENGTH)
                     ^

TypeError: Buffer.alloc is not a function
    at Object.<anonymous> (node_modules/critical/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:6:22)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (node_modules/critical/node_modules/fs-extra/lib/copy-sync/copy-sync.js:5:22)
    at Module._compile (module.js:409:26)
```

**Comment by davidhellmann** [comment]
@melaniegravelnurun I've fixed some Bugs in the Prototype Version. Most of this are in the _modules.scss and app.js 

Can you try to rerun yo from scratch? And maybe with yarn? https://github.com/yarnpkg/yarn

**Comment by melaniegravelnurun** [comment]
Now, 'yo dhboilerplate' gives me this : 

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Missing catch or finally after try in .nvm/versions/node/v4.4.5/lib/node_modules/generator-dhboilerplate/app/templates/___src/assets/css/_modules.scss while compiling ejs
```

**Comment by davidhellmann** [comment]
I'm on Node v7.5.0
Maybe thats a Problem when I'm right you're on 4.4.5?

**Comment by davidhellmann** [comment]
Looks like another problem. I take a look.

**Comment by davidhellmann** [comment]
Please try again @melaniegravelnurun  :)

**Comment by melaniegravelnurun** [comment]
Switched to Node 7.5 just to be sure. Still have

```
SyntaxError: Missing catch or finally after try in .nvm/versions/node/v7.5.0/lib/node_modules/generator-dhboilerplate/app/templates/___src/assets/js/app.js while compiling ejs 
```

**Comment by davidhellmann** [comment]
I've fixt this bugs now. Runs fine here. When not I take a look tomorrow, sorry.

**Comment by melaniegravelnurun** [comment]
Tried with Node 7.7.3 AND yarn and worked. Thank you!
