### ISSUE TITLE
jQuery is Yes, but Vue is No - Error in Scaffolding/Installation

### ISSUE THREAD

**Issue by sumnermic** [davidhellmann/generator-dhBoilerplate#39]
**Nature of Issue:**
Scaffolding is stopped because of package.json error at Line 144, if jQuery is Yes, but Vue is No.

**How to Replicate:**
Choose the WordPress Install, but 'Yes' jQuery, 'No' Vue.js. This will cause an error as the package.json file is invalid.
`package.json Line 144:     "jquery": "./node_modules/jquery/dist/jquery.js",`
**How to Solve:**
Remove the comma `,` if only one of these Browser dependencies are within the package.json file.

For more information, please try [json-linting](http://jsonlint.com/), [this package.json file](https://gist.github.com/sumnermic/cfaae6edde65e50098d1298bfc5f9cc2) in the error.

**Comment by davidhellmann** [comment]
Ah, I see the problem:

```
  "browser": {
    <% if (projectjQuery) { %>
    "jquery": "./node_modules/jquery/dist/jquery.js",
    <% } %>
    <% if (projectVue == true ) { %>
    "vue": "vue/dist/vue.common",
    <% } %>
  },
```

Currently I work a bit in the refactoring branch and Hope I can fix it there and push it back to the master. Thanks!

**Comment by davidhellmann** [comment]
Fixed
