### ISSUE TITLE
Yeoman generator not working

### ISSUE THREAD

**Issue by dedaluz** [davidhellmann/generator-dhBoilerplate#49]
```
TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (/Users/albertpi/.nvm/versions/node/v6.5.0/lib/node_modules/generator-dhboilerplate/app/index.js:12:43
```

**Comment by davidhellmann** [comment]
Which Node Version? here it works fine. Please update the generator and try again please

**Comment by dedaluz** [comment]
Tried with node 6.5.0 and 8.0.0. Latest dhBoilerplate, latest npm, latest yeoman too.

**Comment by davidhellmann** [comment]
hm. strange. look at it tomorrow. Tried it today and all fine. 
When comes the error?

**Comment by dedaluz** [comment]
Thanks. Starting a dh-Boilerplate project (or upgrading an existing one) with Yeoman.

it refers to: index.js:12:43

**Comment by davidhellmann** [comment]
@dedaluz I've pushed an update. I downgraded the generator for now. Looks like there are a lot line to rewrite but no time for this at the moment.

**Comment by dedaluz** [comment]
Working now for me :)
